spring.config.import=optional:classpath:secret.properties

spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://it23322530_db_user:hs7xzv1c2ynwHSdQ@cluster0.xiyti8v.mongodb.net/smart-campus?appName=Cluster0&retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

server.port=5000

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.mongodb.client=INFO

# Allow the React frontend to communicate with this backend
spring.mvc.cors.allowed-origins=http://localhost:5173

# OAuth 2.0 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Admin Configuration
app.admin.email=${ADMIN_EMAIL:admin@campus.edu}

# File Upload Configuration
app.upload.dir=${UPLOAD_DIR:./uploads}